### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by jmenglis** [sbrunswig/cssalchemy-old#2]
@RossLitzenberger do you happen to know if this project is abandoned?  It seem as if @sbrunswig never completed the work.

**Comment by jmenglis** [comment]
mt--

**Comment by RossLitzenberger** [comment]
https://cdn.drawception.com/images/panels/2015/8-13/js2htFXg3Y-10.png

**Comment by RossLitzenberger** [comment]
# memes <img src="https://cdn.drawception.com/images/panels/2015/8-13/js2htFXg3Y-10.png">

**Comment by jmenglis** [comment]
**MEMES!**

**Comment by jmenglis** [comment]
Closed due to inactivity by the repository owner and

# MEMES

**Comment by sbrunswig** [comment]
project is going public, stay tunned for more updates, in process of getting funding from dogecoin investments

**Comment by jmenglis** [comment]
I've been tuned in since August 2017.
